# Kiểm tra mô hình phân loại

## 1.Ma trận nhầm lẫn
* Tên Tiếng Anh: **confusion matrix**
* Kích thước của ma trận: $C \times C$; với $C$ là số lớp của bài toán phân loại.
* **hàng**: nhãn đúng  
* **cột**: dự báo của mô hình

$
M = \left[
\begin{align}
& \quad \text{Dự báo: Positive} &\quad \text{Dự báo: Nagative} \\
\hline
\text{Nhãn: Positive} &\quad \mathbb{True Positive} &\quad \mathbb{False Negative} \\
\text{Nhãn: Negative} &\quad \mathbb{False Positive}  &\quad \mathbb{True Negative}
\end{align}
\right]
$


**Tham khảo thêm:**
[Confusion Matrix](https://en.wikipedia.org/wiki/Confusion_matrix)

### 1.1 Minh họa

* Giả sử có mô hình dự báo đã được huấn luyện để phân loại mỗi mẫu dữ liệu (ví dụ: ảnh) vào một trong hai loại sau:
    *  Ác tính (Malignant), còn được là mẫu dương (**Positive**)
    *  Lành tính (Benign), mẫu âm (**Negative**)
* Khi kiểm tra mô hình nói trên với một tập dữ liệu có $114$ mẫu, với phân bố sau, ta thu được kết quả như trình bày trong ma trận nhầm lẫn $M$, cho bên dưới:
    * 47 điểm dữ liệu được gán nhãn **Ác tính** (Positive)
    * 67 điểm dữ liệu được gán nhãn **Lành tính** (Negative)
    
**Ma trận nhầm lẫn**:



$
M =
\left[
\begin{align}
& \quad \text{Positive} &\quad \text{Nagative} \\
\hline
\text{Positive} &\quad 45 &\quad 2 \\
\text{Negative} &\quad 4  &\quad 63
\end{align}
\right]
$


Thông tin từ ma trận $M$:
* Trong số $47$ mẫu ác tính được gán nhãn thì có:
    * $45$ mẫu cũng được dự báo là ác tính; kết quả này được gọi là **dương tính thật** hay **True Positive**
    * $2$ mẫu bị gán nhầm là lành tính (negative), còn được gọi là **âm tính giả** (**False Negative**)
* Trong số $67$ mẫu lành tính được gán nhãn thì có:
    * $63$ mẫu cũng được dự báo là lành tính; kết quả này được gọi là **âm tính thật** hay **True Negative**
    * $4$ mẫu bị gán nhầm là ác tính (positive), còn được gọi là **dương tính giả** (**False Positive**)

### 1.2 Cách xây dựng ma trận nhầm lẫn

Ma trận nhầm lẫn được xây dựng từ hai véctơ:
*  Véctơ chứa nhãn đúng cho các điểm dữ liệu (**target**)
*  Véctơ chứa nhãn dự báo từ mô hình cho các điểm dữ liệu (**prediction**)

Với bài toán phân loại có $C$ lớp thì chỉ số các nhãn sẽ thuộc $[0, C)$. Ví dụ, C=3 thì các chỉ số của các nhãn là: $0, 1, 2$. Do đó, **target** và **prediction** chứa các giá trị thuộc $[0, C)$. Hai véctơ **target** và **prediction** phải có chiều dài bằng nhau, và bằng số lượng mẫu dữ liệu được đánh giá.

**Ví dụ**:
* Số lớp là 3: $C=3$
* Kích thước của ma trận nhẫm lẫn: $3 \times 3$
* Giả sử:
    *  **target**: $[0, 2, 1, 0]$
    *  **prediction**: $[0, 0, 2, 0]$
    *  Ta có các cặp (**nhãn**, **dự báo**): $(0, 0), (2, 0), (1, 2), (0, 0)$

**Các bước**:
* Khởi động:
$
M =
\left[
\begin{align}
0 \quad 0 \quad 0\\
0 \quad 0 \quad 0\\
0 \quad 0 \quad 0
\end{align}
\right]
$
* Xét cặp (**nhãn**, **dự báo**): (0,0) => **dự báo đúng**
    * Tăng giá trị $M[0,0] = M[0,0] + 1$; được ma trận
$
M =
\left[
\begin{align}
1 \quad 0 \quad 0\\
0 \quad 0 \quad 0\\
0 \quad 0 \quad 0
\end{align}
\right]
$
* Xét cặp (**nhãn**, **dự báo**): (2,0) => **dự báo sai**: nhãn là $2$ bị nhầm sang $0$
    * Tăng giá trị $M[2,0] = M[2,0] + 1$; được ma trận
$
M =
\left[
\begin{align}
1 \quad 0 \quad 0\\
0 \quad 0 \quad 0\\
1 \quad 0 \quad 0
\end{align}
\right]
$    
* Xét cặp (**nhãn**, **dự báo**): (1,2) => **dự báo sai**: nhãn là $1$ bị nhầm sang $2$
    * Tăng giá trị $M[1,2] = M[1,2] + 1$; được ma trận
$
M =
\left[
\begin{align}
1 \quad 0 \quad 0\\
0 \quad 0 \quad 1\\
1 \quad 0 \quad 0
\end{align}
\right]
$    
* Xét cặp (**nhãn**, **dự báo**): (0,0) => **dự báo đúng**:
    * Tăng giá trị $M[0,0] = M[0,0] + 1$; được ma trận
$
M =
\left[
\begin{align}
2 \quad 0 \quad 0\\
0 \quad 0 \quad 1\\
1 \quad 0 \quad 0
\end{align}
\right]
$    

### 1.3 Lập trình

In [ ]:
import numpy as np

#Ma trận nhầm lẫn

'''
nclasses is None: nclases = giá trị lớn nhất trong target + 1
'''
def cmatrix(target, prediction, nclasses=None):
    if nclasses is None:
        C = target.max() + 1
    else:
        C = nclasses
    N = target.shape[0]
    M = np.zeros((C, C, N), dtype=np.int64)
    M[target.ravel(), prediction.ravel(), np.arange(N)] = 1
    return M.sum(axis=2)

'''
pdiff => (1-pdiff)*100% prediction có nhãn giống target
'''
def gen_target_prediction(nclasses, nsamples, pdiff=0.2):
    #sinh dữ liệu:
    C = nclasses; N = nsamples
    target = np.random.randint(0, C, (N,))
    prediction = target.copy()
    change = np.random.randint(0, N, (int(N*pdiff),))
    import random
    for tidx in change:
        labels = list(range(C))
        labels.remove(target[tidx])
        changeto = random.choice(labels)
        prediction[tidx] = changeto
    return target, prediction

C = 5
target, prediction = gen_target_prediction(5, 500, 0.2)
M = cmatrix(target, prediction, C)
print(M)



[[90  5  7  4  2]
 [ 3 79  2  7 10]
 [ 5  5 82  8  4]
 [ 5  3  4 85  7]
 [ 1  1  5  3 73]]


## 2. Các độ đo đánh giá:

**Ma trận nhầm lẫn**:

$
M = \left[
\begin{align}
& \quad \text{Dự báo: Positive} &\quad \text{Dự báo: Nagative} \\
\hline
\text{Nhãn: Positive} &\quad \mathbb{True Positive} &\quad \mathbb{False Negative} \\
\text{Nhãn: Negative} &\quad \mathbb{False Positive}  &\quad \mathbb{True Negative}
\end{align}
\right]
$

### 2.1 Độ chính xác
* Công thức: $precision = \frac{TruePositive}{TruePositive + FalsePositive}$
* Cũng có nghĩa: tổng số mẫu mô hình dự báo **đúng** cho nhãn X chia cho tổng số mẫu mô hình dự báo là nhãn X
* Giá **trị nằm trên đường chéo** chia cho **tổng giá trị trên cột** của ma trận nhầm lẫn

### 2.2 Độ triệu hồi/độ phủ
* Công thức: $recall = \frac{TruePositive}{TruePositive + FalseNegative}$
* Cũng có nghĩa: tổng số mẫu mô hình dự báo **đúng** cho nhãn X chia cho tổng số mẫu được gán (được làm nhãn) là nhãn X
* Giá **trị nằm trên đường chéo** chia cho **tổng giá trị trên hàng** của ma trận nhầm lẫn

### 2.3 F1-Score
* Công thức: $F_1 = 2\times \frac{precision \times recall}{precision + recall} = \frac{2\times TruePositive}{2\times TruePositive + FalseNegative + TrueNegative}$
* **Hai lần giá trị nằm trên đường chéo** chia cho **tổng giá trị giá trị trên hàng và trên cột** giao nhau tại giá trị nằm trên đường chéo đang xem xét

### 2.4 Accuracy
* Công thức: $Accuracy = \frac{TruePositive + TrueNegative}{TruePositive + TrueNegative + FalsePositive + FalseNegative}$
* Cũng có nghĩa: tổng số mẫu mô hình dự báo **đúng** cho tất cả các nhãn chia cho tổng số mẫu có trong tập dữ liệu đánh giá
* **Tổng giá trị nằm trên đường chéo** chia cho **tổng giá trị của toàn bộ ma trận nhầm lẫn**

### 2.5 Minh họa

**Ma trận nhầm lẫn**:

$
M =
\left[
\begin{align}
& \quad \text{Positive} &\quad \text{Nagative} \\
\hline
\text{Positive} &\quad 45 &\quad 2 \\
\text{Negative} &\quad 4  &\quad 63
\end{align}
\right]
$

**Độ chính xác (precision)**:
* Độ chính xác của mô hình với nhãn **Dương** là: $(45/(45 + 4)) \sim 0.92$
* Độ chính xác của mô hình với nhãn **Âm** là: $(63/(63 + 2)) \sim 0.97$
* Độ chính xác trung bình là: $(0.92 + 0.97)/2 \sim 0.94$
* Độ chính xác trung bình **có trọng số** là: $0.92 \times [47/114] + 0.97 \times [67/114] \sim 0.95$

**Độ phủ**:
* Độ phủ của mô hình với nhãn **Dương** là: $(45/(45 + 2)) \sim 0.96$
* Độ phủ của mô hình với nhãn **Âm** là: $(63/(63 + 4)) \sim 0.94$
* Độ phủ trung bình là: $(0.96 + 0.94)/2 \sim 0.95$
* Độ phủ trung bình **có trọng số** là: $0.96 \times [47/114] + 0.94 \times [67/114] \sim 0.95$

**Độ đo F1**
* **F1-Measure** của mô hình với nhãn **Dương** là: $2 \times [0.92 \times 0.96]/[0.92 + 0.96] \sim 0.94$
* **F1-Measure** của mô hình với nhãn **Âm** là: $2 \times [0.97 \times 0.94]/[0.97 + 0.94] \sim 0.95$
* **F1-Measure** trung bình là: $(0.94 + 0.95)/2 \sim 0.95$
* **F1-Measure** trung bình **có trọng số** là: $0.94 \times [47/114] + 0.95 \times [67/114] \sim 0.95$

**Độ chính xác (accuracy)**:
* Độ chính xác (accuracy) của mô hình là: $(45 + 63)/(45 + 63 + 2 + 4) = 108/114 \sim 0.95$

### 2.6 Lập trình


In [ ]:
import numpy as np
np.set_printoptions(precision=2)

def precision(target, prediction, nclasses=None):
    M = cmatrix(target, prediction, nclasses)
    if nclasses is None:
        C = target.max() + 1
    else:
        C = nclasses
    weights = M.sum(axis=1)/M.sum()
    prec_per_class = M[np.arange(C), np.arange(C)]/M.sum(axis=0)
    prec_averaged = prec_per_class.mean()
    prec_weighted = (prec_per_class*weights).sum()
    return prec_per_class, prec_averaged, prec_weighted

def recall(target, prediction, nclasses=None):
    M = cmatrix(target, prediction, nclasses)
    if nclasses is None:
        C = target.max() + 1
    else:
        C = nclasses

    weights = M.sum(axis=1)/M.sum()
    rec_per_classes =  M[np.arange(C), np.arange(C)]/M.sum(axis=1)
    prec_averaged = rec_per_classes.mean()
    prec_weighted = (rec_per_classes*weights).sum()

    return rec_per_classes, prec_averaged, prec_weighted

def f1_measure(target, prediction, nclasses=None):
    prec, _, _ = precision(target, prediction, nclasses)
    rec, _, _ = recall(target, prediction, nclasses)
    M = cmatrix(target, prediction, nclasses)
    if nclasses is None:
        C = target.max() + 1
    else:
        C = nclasses

    weights = M.sum(axis=1)/M.sum()
    f1_per_classes =  2*prec*rec/(prec+rec)
    f1_averaged = f1_per_classes.mean()
    f1_weighted = (f1_per_classes*weights).sum()

    return f1_per_classes, f1_averaged, f1_weighted

def accuracy(target, prediction, nclasses=None):
    M = cmatrix(target, prediction, nclasses)
    if nclasses is None:
        C = target.max() + 1
    else:
        C = nclasses
    return M[np.arange(C), np.arange(C)].sum()/M.sum()

C = 5
target, prediction = gen_target_prediction(C, 500, 0.1)
prec_per_classes, prec_averaged, prec_weighted = precision(target, prediction, C)
rec_per_classes, rec_averaged, rec_weighted = recall(target, prediction, C)
f1_per_classes, f1_averaged, f1_weighted = f1_measure(target, prediction, C)
acc = accuracy(target, prediction, C)

print('precision:')
print('\t', prec_per_classes)
print('\t', prec_averaged)
print('\t', prec_weighted)

print('recall:')
print('\t', rec_per_classes)
print('\t', rec_averaged)
print('\t', rec_weighted)

print('f1:')
print('\t', f1_per_classes)
print('\t', f1_averaged)
print('\t', f1_weighted)

print('accuracy: ', acc)

precision:
	 [0.91 0.86 0.92 0.91 0.91]
	 0.900002834347102
	 0.9023323591705387
recall:
	 [0.9  0.89 0.91 0.91 0.9 ]
	 0.9012647096857623
	 0.9020000000000001
f1:
	 [0.9  0.87 0.92 0.91 0.9 ]
	 0.9005641330302744
	 0.9021066484163476
accuracy:  0.902



## 3. Ứng dụng trong bài toán phân loại

**Tham khảo**
* Nên sử dụng thư viện **scikit-learn**: [classification_report](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html)
    

In [ ]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

#Nạp dữ liệu + chia tách
dataset = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    dataset.data, dataset.target, test_size=0.2, random_state=0)

#Học máy
model = LogisticRegression(max_iter=10000).fit(X_train, y_train)
y_pred = model.predict(X_test)

#from sklearn
print('REPORT FROM SKLEARN: ')
print(classification_report(y_test, y_pred, target_names=dataset.target_names))

#your API
print('#'*100)
print('YOUR REPORT: ')
C = len(dataset.target_names)
prec_per_classes, prec_averaged, prec_weighted = precision(y_test, y_pred, C)
rec_per_classes, rec_averaged, rec_weighted = recall(y_test, y_pred, C)
f1_per_classes, f1_averaged, f1_weighted = f1_measure(y_test, y_pred, C)
acc = accuracy(y_test, y_pred, C)

print('precision:')
print('\tprec_per_classes:', prec_per_classes)
print('\tprec_averaged:{:7.2f}'.format(prec_averaged))
print('\tprec_weighted:{:7.2f}'.format(prec_weighted))

print('recall:')
print('\trec_per_classes:', rec_per_classes)
print('\trec_averaged:{:7.2f}'.format(rec_averaged))
print('\trec_weighted:{:7.2f}'.format(rec_weighted))

print('f1:')
print('\tf1_per_classes:', f1_per_classes)
print('\tf1_averaged:{:7.2f}'.format(f1_averaged))
print('\tf1_weighted:{:7.2f}'.format(f1_weighted))

print('accuracy: {:7.2f}'.format(acc))


REPORT FROM SKLEARN: 
              precision    recall  f1-score   support

   malignant       0.90      0.98      0.94        47
      benign       0.98      0.93      0.95        67

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.95       114
weighted avg       0.95      0.95      0.95       114

####################################################################################################
YOUR REPORT: 
precision:
	prec_per_classes: [0.9  0.98]
	prec_averaged:   0.94
	prec_weighted:   0.95
recall:
	rec_per_classes: [0.98 0.93]
	rec_averaged:   0.95
	rec_weighted:   0.95
f1:
	f1_per_classes: [0.94 0.95]
	f1_averaged:   0.95
	f1_weighted:   0.95
accuracy:    0.95
